# Generated by Django 5.2.12 on 2026-04-09 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestGenerationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="未命名配置", max_length=100, verbose_name="配置名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="配置描述")),
                ("chapters", models.JSONField(default=list, verbose_name="知识点章节")),
                (
                    "knowledge_categories",
                    models.JSONField(default=list, verbose_name="知识点分类"),
                ),
                (
                    "knowledge_points",
                    models.JSONField(default=list, verbose_name="知识点"),
                ),
                (
                    "question_types",
                    models.JSONField(default=list, verbose_name="题型选择"),
                ),
                (
                    "output_answer",
                    models.BooleanField(default=True, verbose_name="是否输出答案"),
                ),
                (
                    "output_explanation",
                    models.BooleanField(default=True, verbose_name="是否输出解析"),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("json", "JSON格式"),
                            ("markdown", "Markdown格式"),
                            ("text", "纯文本格式"),
                            ("html", "HTML格式"),
                        ],
                        default="json",
                        max_length=20,
                        verbose_name="输出格式",
                    ),
                ),
                (
                    "use_knowledge_graph",
                    models.BooleanField(default=True, verbose_name="使用知识图谱"),
                ),
                (
                    "use_rag_retrieval",
                    models.BooleanField(default=True, verbose_name="使用RAG检索"),
                ),
                (
                    "difficulty_level",
                    models.IntegerField(
                        choices=[(1, "简单"), (2, "中等"), (3, "困难")],
                        default=2,
                        verbose_name="难度级别",
                    ),
                ),
                (
                    "question_count",
                    models.IntegerField(default=5, verbose_name="题目数量"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("zh", "中文"), ("en", "英文")],
                        default="zh",
                        max_length=20,
                        verbose_name="题目语言",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "测试题生成配置",
                "verbose_name_plural": "测试题生成配置",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "questions",
                    models.JSONField(default=list, verbose_name="生成的题目"),
                ),
                ("raw_response", models.TextField(blank=True, verbose_name="原始响应")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "生成中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("partial", "部分成功"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "generation_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="生成耗时(秒)"
                    ),
                ),
                (
                    "token_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Token数量"
                    ),
                ),
                (
                    "retrieved_docs",
                    models.JSONField(
                        blank=True, default=list, verbose_name="检索的文档"
                    ),
                ),
                (
                    "kg_entities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="知识图谱实体"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_tests",
                        to="experts.testgenerationconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "生成的测试题",
                "verbose_name_plural": "生成的测试题",
                "ordering": ["-created_at"],
            },
        ),
    ]
