# Generated by Django 5.2.12 on 2026-04-20 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "knowledge_point",
                    models.CharField(max_length=200, verbose_name="所属知识点"),
                ),
                ("chapter", models.CharField(max_length=200, verbose_name="所属章节")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single_choice", "单选题"),
                            ("multi_choice", "多选题"),
                            ("judge", "判断题"),
                            ("fill_blank", "填空题"),
                            ("short_answer", "简答题"),
                        ],
                        max_length=50,
                        verbose_name="题型",
                    ),
                ),
                ("difficulty", models.CharField(max_length=10, verbose_name="难度")),
                ("question_text", models.TextField(verbose_name="题目内容")),
                (
                    "options",
                    models.JSONField(
                        blank=True, null=True, verbose_name="选项（选择题专用）"
                    ),
                ),
                ("answer", models.CharField(max_length=200, verbose_name="答案")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试题",
                "verbose_name_plural": "测试题",
                "db_table": "question",
            },
        ),
        migrations.CreateModel(
            name="TaskInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="主键"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="任务创建时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="任务完成时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发起人",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务信息",
                "verbose_name_plural": "任务信息",
                "db_table": "task_info",
                "ordering": ["-created_at"],
            },
        ),
    ]
