# Generated by Django 5.2.12 on 2026-04-20 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200, verbose_name="章节标题")),
                (
                    "book_name",
                    models.CharField(max_length=200, verbose_name="教材名称"),
                ),
            ],
            options={
                "verbose_name": "章节信息",
                "verbose_name_plural": "章节信息",
                "db_table": "chapter",
            },
        ),
        migrations.CreateModel(
            name="KnowledgePoint",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200, verbose_name="知识点内容")),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_points",
                        to="course.chapter",
                        verbose_name="所属章节",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识点",
                "verbose_name_plural": "知识点",
                "db_table": "knowledge_point",
            },
        ),
    ]
