# Generated by Django 5.2.12 on 2026-04-20 17:41

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="唯一ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="会话ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="会话标题"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        default="qwen3:4b",
                        max_length=100,
                        verbose_name="模型名称",
                    ),
                ),
                (
                    "chat_history",
                    models.JSONField(
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="聊天历史",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天会话",
                "verbose_name_plural": "聊天会话管理",
                "db_table": "chat_session",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "updated_at"],
                        name="chat_sessio_user_id_84384d_idx",
                    ),
                    models.Index(
                        fields=["session_id"], name="chat_sessio_session_b18b4a_idx"
                    ),
                ],
            },
        ),
    ]
